global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'poa'
    static_configs:
      - targets:
        - 'host.docker.internal:6060'  # node1
        - 'host.docker.internal:6061'  # node2
        - 'host.docker.internal:6062'  # node3
    metrics_path: /debug/metrics/prometheus